language: android

scala:
  - "2.11.7"

android:
  components:
    - android-22
    - extra
    - platform-tools
    - tools

script: wget https://raw.github.com/paulp/sbt-extras/master/sbt && chmod u+x ./sbt && ./sbt test
